services:
    php:
        build:
            dockerfile: './docker/php/Dockerfile'
        container_name: 'crafting-php'
        volumes:
            - '.:/var/www/html'
            - './docker/crontabs:/etc/cron.d'
            - './docker/supervisor/log:/var/log'
            - './docker/8.2:/etc/supervisor/conf.d'
            - './docker/storage/logs/supervisor:/var/log/supervisor'
        networks:
            - 'sail'
    nginx:
        image: 'nginx:latest'
        container_name: 'crafting-nginx'
        ports:
            - '${APP_PORT:-8000}:80'
        networks:
            - 'sail'
        volumes:
            - './docker/nginx/logs/access.log:/var/log/nginx/access.log'
            - './docker/nginx/logs/error.log:/var/log/nginx/error.log'
    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: 'crafting-mysql'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '${DB_HOST}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: '0'
        volumes:
            - './docker/mysql/:/var/lib/mysql'
        networks:
            - 'sail'
        healthcheck:
            test:
                - 'CMD'
                - 'mysqladmin'
                - 'ping'
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: '5s'
    redis:
        image: 'redis:alpine3.16'
        container_name: 'crafting-redis'
        volumes:
            - './docker/redis/:/var/www/html/docker/redis/'
            - './docker/cache/data:/data'
        command: 'redis-server --save 20 1 --loglevel warning'
        ports:
            - '6379:6379'
        networks:
            - 'sail'
networks:
    sail:
        driver: 'bridge'
volumes:
    sail-mysql:
        driver: 'local'
